import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type Lang = 'pt' | 'en' | 'es';

type IdiomaContextType = {
  idioma: Lang;
  setIdioma: (l: Lang) => void;
  t: (key: string) => string;
};

const translations: Record<Lang, Record<string, string>> = {
  pt: {
    voltar: 'Voltar',
    idioma: 'Idioma',
    portugues: 'Português (Brasil)',
    english: 'English',
    spanish: 'Español',
    aplicacoes_idioma: 'As configurações de idioma serão aplicadas imediatamente',
    configuracoes: 'Configurações',
    editar_perfil: 'Editar Perfil',
    alterar_dados: 'Altere seus dados pessoais',
    cadastro_titulo: 'Cadastro',
    cadastro_passo1: 'Preencha seus dados pessoais',
    cadastro_passo2: 'Configure sua senha e preferências',
    label_nome: 'Nome completo',
    label_email: 'Email',
    label_cpf: 'CPF',
    label_nascimento: 'Data de nascimento',
    label_telefone: 'Telefone',
    label_senha: 'Senha',
    label_confirmar_senha: 'Confirmar senha',
    cadastro_proxima_etapa: 'Próxima etapa',
    cadastro_cadastrar: 'Cadastrar',
    cadastro_voltar: 'Voltar',
    cadastro_erro_nome_curto: 'Nome muito curto',
    placeholder_nome: 'Digite seu nome completo',
    placeholder_email: 'Digite seu e-mail',
    placeholder_cpf: 'Digite seu CPF',
    placeholder_nascimento: 'DD/MM/AAAA',
    placeholder_telefone: '(99) 99999-9999',
    placeholder_senha: 'Crie uma senha',
    placeholder_confirmar_senha: 'Confirme sua senha',
    cadastro_li_concordo: 'Li e concordo com os',
    login_entrar: 'Entrar',
    login_esqueci_senha: 'Esqueci minha senha',
    login_nao_tem_conta: 'Não tem uma conta?',
    ou_text: 'ou',
    login_continuar_convidado: 'Continuar como convidado',
    cadastre_se: 'Cadastre-se',
    nav_inicio: 'Início',
    nav_analise: 'Análise',
    nav_dados: 'Dados',
    nav_perfil: 'Perfil',
    nav_config: 'Config',
    inicio_ola_bemvindo: 'Olá, Bem-vindo(a)',
    inicio_subtitulo: 'Monitore a saúde dos seus olhos regularmente',
    inicio_iniciar_analise: 'Iniciar Análise',
    inicio_analise_rapida: 'Análise rápida em menos de 1 minuto',
    tutorial_titulo: 'Tutorial',
    tutorial_desc: 'Aprenda a utilizar o aplicativo',
    tutorial_step1_title: 'Bem-vindo ao Tutorial',
    tutorial_step1_desc: 'Vamos aprender a realizar uma análise usando o Eyessistant!\n\nEste tutorial mostra passo a passo como posicionar o celular e tirar fotos de qualidade. Se você for idoso ou tiver pouca familiaridade com smartphones, peça ajuda a alguém ou siga cada passo com calma.',
    tutorial_step1_tip1: 'Escolha um local com boa iluminação difusa (não aponte o rosto para luz direta).',
    tutorial_step1_tip2: 'Sente-se em uma cadeira confortável com apoio para os braços.',
    tutorial_step1_tip3: 'Segure o celular com firmeza ou apoie em uma superfície estável (mesa, suporte).',
    tutorial_step1_tip4: 'Respire fundo e mantenha o olhar estável por alguns segundos antes da captura.',

    tutorial_step2_title: 'Peça Ajuda',
    tutorial_step2_desc: 'Ter alguém para ajudar torna o processo mais fácil: a pessoa pode segurar o celular, ajustar o ângulo e garantir que o olho esteja bem enquadrado. Se estiver sozinho, apoie o celular contra algo estável.',
    tutorial_step2_tip1: 'Peça para a pessoa ficar ao seu lado e seguir as orientações do app.',
    tutorial_step2_tip2: 'Explique que é preciso centralizar o olho no quadro e manter distância de 10–15 cm.',
    tutorial_step2_tip3: 'Peça para não usar flash diretamente no olho (iluminação constante é melhor).',

    tutorial_step3_title: 'Posicione o Celular',
    tutorial_step3_desc: 'Sente-se confortavelmente e apoie o celular em uma superfície estável para evitar tremores. Aponte a câmera para o olho a uma distância de 10–15 cm para garantir um bom enquadramento e foco. Mantenha o olho aberto, olhando para a câmera.',
    tutorial_step3_tip1: 'Remova óculos, lentes de contato, chapéus ou máscaras antes da captura.',
    tutorial_step3_tip2: 'Evite fundos muito claros ou muito escuros atrás do rosto (use parede neutra quando possível).',
    tutorial_step3_tip3: 'Se o foco estiver ruim, mova o celular um pouco mais perto ou mais longe até a imagem ficar nítida.',

    tutorial_step4_title: 'Envio e Análise',
    tutorial_step4_desc: 'Após capturar a imagem, ela será enviada para análise por nossa IA. O processamento pode levar alguns segundos a alguns minutos, dependendo da conexão. Enquanto isso, não feche o app. Quando os resultados aparecerem, leia com atenção e siga recomendações.',
    tutorial_step4_tip1: 'Aguarde a mensagem de conclusão antes de navegar para outra tela.',
    tutorial_step4_tip2: 'Verifique os detalhes da análise — se algo parecer errado, repita a captura com melhor iluminação.',
    tutorial_step4_tip3: 'Se houver indicação de problema, procure um oftalmologista para avaliação presencial.',

    dica_label: 'Dica:',
    sair: 'Sair',
    proximo: 'Próximo',
    finalizar: 'Finalizar',
    inicio_ultima_analise: 'Última Análise',
    inicio_ver_todos: 'Ver todos',
    historico_nenhum_sinal: 'Nenhum sinal detectado',
    historico_possiveis_sinais: 'Possíveis sinais iniciais',
    dica_saude_titulo: 'Dica de Saúde Ocular',
    dica_saude_body: 'Fazer pausas regulares ao usar dispositivos digitais ajuda a reduzir a fadiga ocular.\nSiga a regra 20-20-20: a cada 20 minutos, olhe para algo a 20 pés (6 metros) por 20 segundos.',
    alert_preencha_campos: 'Preencha todos os campos corretamente.',
    alert_corrija_erros: 'Corrija os erros antes de continuar.',
    alert_preencha_aceite: 'Preencha todos os campos e aceite os termos.',
    email_invalido: 'Email inválido',
    cpf_invalido: 'CPF inválido',
    data_invalida: 'Data inválida',
    telefone_invalido: 'Telefone inválido',
    senha_fraca: 'Senha fraca',
    senhas_nao_conferem: 'Senhas não conferem',
    modal_cadastro_titulo: 'Cadastro realizado!',
    modal_cadastro_subtitulo: 'Sua conta foi criada com sucesso.',
    idioma_selecionado: 'Português (Brasil)',
    meus_dados_visao: 'Meus Dados de Visão',
    visao_geral: 'Visão Geral',
    historico: 'Histórico',
    recomendacoes: 'Recomendações',
    status_atual: 'Status Atual da Visão',
    detalhes: 'Detalhes',
    resumo_resultados: 'Resumo dos Resultados',
    evolucao_resultados: 'Evolução dos Resultados',
    historico_completo: 'Histórico Completo',
    analises_por_mes: 'Análises por Mês',
    recomendacoes_personalizadas: 'Recomendações Personalizadas',
    consulta_recomendada: 'Consulta Oftalmológica Recomendada',
    proxima_triagem: 'Próxima Triagem',
    ha_bitossaudaveis: 'Hábitos Saudáveis',
    saiba_mais: 'Saiba Mais',
    o_que_e_catarata: 'O que é catarata?',
    prevencao_catarata: 'Prevenção da catarata',
    tratamentos_disponiveis: 'Tratamentos disponíveis',
    normal: 'Normal',
    atencao: 'Atenção',
    critico: 'Crítico',
    jan: 'Jan',
    fev: 'Fev',
    mar: 'Mar',
    abr: 'Abr',
    mai: 'Mai',
    jun: 'Jun',
    encontrar_oftalmologistas_proximos: 'Encontrar oftalmologistas próximos',
    analises_sem_sinais: '4 análises sem sinais detectados',
    analises_com_possiveis_sinais: '3 análises com possíveis sinais',
    catarata_body: 'A catarata é a opacificação do cristalino (a lente natural do olho) que reduz a quantidade de luz que chega à retina. Pode causar visão embaçada, sensibilidade à luz e dificuldade para enxergar à noite. É comum em pessoas mais velhas, mas pode ocorrer por outras causas.\n\nSinais e sintomas típicos:\n• Visão embaçada ou fosca\n• Aumento da sensibilidade à luz\n• Dificuldade para enxergar à noite\n• Mudanças frequentes na graduação dos óculos\n\nSe notar esses sinais, procure um oftalmologista para avaliação e orientações.',
    prevencao_body: 'Medidas que ajudam a reduzir o risco ou atrasar a progressão da catarata:\n\n• Proteção UV: use óculos de sol com proteção UV adequada sempre que estiver ao ar livre.\n• Evitar tabagismo: fumar aumenta o risco de desenvolvimento de diversas doenças oculares.\n• Alimentação balanceada: dieta rica em frutas e vegetais que contenham antioxidantes (vitaminas A, C, E) é benéfica.\n• Controle de doenças crônicas: mantenha diabetes e pressão arterial sob controle.\n• Exames periódicos: faça avaliações oftalmológicas regulares para detectar alterações precocemente.\n\nEssas medidas não garantem prevenção absoluta, mas reduzem fatores de risco conhecidos.',
    tratamentos_body: 'O tratamento definitivo para catarata é a cirurgia, onde a lente opaca é removida e substituída por uma lente intraocular (LIO).\n\nO que esperar da cirurgia:\n• Procedimento: geralmente realizado com anestesia local e rápida recuperação.\n• Riscos e benefícios: é considerada segura e eficaz, mas discuta possíveis complicações com o oftalmologista.\n• Alternativas temporárias: em fases iniciais, mudanças na correção óptica e melhor iluminação podem melhorar a visão temporariamente.\n\nApós a cirurgia, pode ser necessário algum tempo para adaptar-se à nova lente; o oftalmologista orientará sobre cuidados e retorno.'
    ,
    possivel_opacidade: 'Possível opacidade inicial',
    ultima_atualizacao: 'Última atualização',
    nenhum_problema: 'Nenhum problema detectado',
    consulta_recomendacao_body: 'Com base nas suas últimas análises, recomendamos que você consulte um oftalmologista para uma avaliação mais detalhada.',
    recomendamos_nova_triagem: 'Recomendamos realizar uma nova triagem em',
    agendar_lembrete: 'Agendar lembrete',
    index_detecte_sinais: 'Detecte sinais de catarata com a ajuda da IA',
    index_subtitulo: 'Um exame rápido, acessível e inteligente, usando apenas a câmera do seu celular.',
    index_analise_inteligente: 'Análise Inteligente',
    index_tecnologia_ponta: 'Tecnologia de ponta para detecção precoce de sinais de catarata',
    index_monitoramento_continuo: 'Monitoramento Contínuo',
    index_acompanhe_saude: 'Acompanhe a saúde dos seus olhos com exames periódicos',
    index_privacidade_garantida: 'Privacidade Garantida',
    index_dados_protegidos: 'Seus dados são protegidos e nunca compartilhamos sem sua permissão',
    index_comecar_agora: 'Começar Agora',
    index_termos_politica: 'Ao continuar, você concorda com nossos Termos de Uso e Política de Privacidade',
      index_termos_intro: 'Ao continuar, você concorda com nossos',
      termos_uso: 'Termos de Uso',
      e_text: 'e',
      politica_privacidade: 'Política de Privacidade',
    sobre_app: 'Sobre',
    sobre_o: 'Sobre o',
    sobre_o_eyessistant: 'Sobre o Eyessistant',
    sobre_o_que_e: 'O que é?',
    sobre_o_que_e_body: 'O Eyessistant é um assistente de triagem ocular inteligente que utiliza inteligência artificial para ajudar na detecção precoce de catarata, utilizando apenas a câmera do seu celular para analisar seus olhos.',
    sobre_como_funciona: 'Como funciona?',
    sobre_analise_imagem: 'Análise de Imagem',
    sobre_analise_imagem_body: 'Utilizamos a câmera do seu celular para capturar imagens de alta qualidade dos seus olhos',
    sobre_inteligencia_artificial: 'Inteligência Artificial',
    sobre_inteligencia_body: 'Nossa IA analisa padrões e identifica possíveis sinais de catarata com alta precisão',
    sobre_privacidade: 'Privacidade',
    sobre_privacidade_body: 'Seus dados são processados localmente e protegidos com os mais altos padrões de segurança',
    sobre_por_que_usar: 'Por que usar o Eyessistant?',
    sobre_por_que_usar_body: 'A catarata é uma das principais causas de cegueira tratável no mundo. A detecção precoce é fundamental para um tratamento eficaz e para prevenir a perda de visão. O Eyessistant torna esse processo acessível a todos, a qualquer momento.',
    sobre_disclaimer: 'O Eyessistant não substitui uma consulta com um oftalmologista. Sempre consulte um profissional de saúde para diagnóstico e tratamento adequados.',
    editperfil_titulo: 'Editar Perfil',
    editperfil_permissao_titulo: 'Permissão necessária',
    editperfil_permissao_body: 'Precisamos de acesso às fotos para alterar a foto de perfil.',
    editperfil_salvo_titulo: 'Salvo',
    editperfil_salvo_body: 'Dados do perfil atualizados.',
    editperfil_erro_titulo: 'Erro',
    editperfil_erro_body: 'Não foi possível salvar os dados.',
    alterar_foto: 'Alterar foto',
    placeholder_seu_nome: 'Seu nome',
    salvar: 'Salvar',
    perfil_nenhum_sinal: 'Nenhum sinal detectado',
    perfil_possiveis_sinais: 'Possíveis sinais iniciais',
    perfil_continuar_monitorando: 'Continue monitorando regularmente',
    perfil_recomendamos_acompanhamento: 'Recomendamos acompanhamento',
    perfil_analises_recentes: 'Análises Recentes',
    perfil_editar: 'Editar',
    perfil_config: 'Configuração',
    termos_titulo: 'Termos de Uso',
    termos_ultima_atualizacao: 'Última atualização: 15 de maio de 2024',
    termos_1_aceitacao_titulo: '1. Aceitação dos Termos',
    termos_1_aceitacao_body: 'Ao acessar e utilizar o aplicativo Eyessistant, você concorda com estes Termos de Uso. Se não concordar com alguma parte destes termos, não utilize o aplicativo.',
    termos_2_descricao_titulo: '2. Descrição do Serviço',
    termos_2_descricao_body: 'O Eyessistant é um aplicativo de triagem ocular que utiliza inteligência artificial para identificar possíveis sinais de catarata. O aplicativo NÃO fornece diagnósticos médicos e não substitui o conselho de um profissional de saúde qualificado.',
    termos_importante: 'Importante: Os resultados fornecidos pelo aplicativo são apenas indicativos e devem ser confirmados clinicamente. Consulte um profissional de saúde para avaliação e diagnóstico.',
    termos_3_elegibilidade_titulo: '3. Elegibilidade e Cadastro',
    termos_3_elegibilidade_body: 'Para utilizar o aplicativo, você deve:\n• Ter pelo menos 18 anos de idade;\n• Fornecer informações precisas, atuais e completas durante o cadastro;\n• Manter suas informações de cadastro atualizadas;\n• Ser responsável pela segurança de sua conta e senha.',
    termos_4_uso_titulo: '4. Uso do Aplicativo',
    termos_4_uso_body: 'Ao utilizar o aplicativo, você concorda em:\n• Não utilizar para fins ilegais ou não autorizados;\n• Não tentar acessar áreas restritas do sistema;\n• Não interferir ou interromper o funcionamento do aplicativo;\n• Não reproduzir, copiar, vender ou explorar qualquer parte do aplicativo;\n• Seguir todas as instruções fornecidas para o uso adequado.',
    termos_5_limitacao_titulo: '5. Limitação de Responsabilidade',
    termos_5_limitacao_body: 'O Eyessistant e seus desenvolvedores não são responsáveis por quaisquer danos diretos, indiretos, incidentais ou consequenciais resultantes do uso ou incapacidade de usar o aplicativo. O uso é por sua conta e risco.',
    termos_6_propriedade_titulo: '6. Propriedade Intelectual',
    termos_6_propriedade_body: 'Todo o conteúdo, design, gráficos, interfaces, códigos e software utilizados no aplicativo são de propriedade do Eyessistant ou de seus licenciadores. Você não tem permissão para copiar, modificar, distribuir, vender ou alugar qualquer parte do aplicativo.',
    termos_7_modificacoes_titulo: '7. Modificações dos Termos',
    termos_7_modificacoes_body: 'Reservamos o direito de modificar estes Termos a qualquer momento. As alterações entram em vigor imediatamente após a publicação no aplicativo ou aviso aos usuários.',
    termos_8_lei_titulo: '8. Lei Aplicável',
    termos_8_lei_body: 'Estes Termos são regidos e interpretados de acordo com as leis do Brasil. Qualquer disputa será submetida à jurisdição exclusiva dos tribunais da cidade de São Paulo.',
    termos_9_contato_titulo: '9. Contato',
    termos_9_contato_body: 'Dúvidas sobre estes Termos? Entre em contato pelo e-mail: suporte@eyessistant.com',
    termos_entendi_concordo: 'Entendi e concordo',
    priv_politica_titulo: 'Política de Privacidade',
    priv_ultima_atualizacao: 'Última atualização: 13 de setembro de 2025',
    priv_1_introducao_titulo: '1. Introdução',
    priv_1_introducao_body: 'A Eyessistant está comprometida em proteger sua privacidade. Esta Política descreve como coletamos, usamos e protegemos suas informações ao utilizar o aplicativo Eyessistant.',
    priv_2_informacoes_titulo: '2. Informações que Coletamos',
    priv_2_informacoes_body: '• Dados pessoais: nome, e-mail, telefone e CPF (quando fornecidos).\n• Dados de saúde: informações sobre sua visão, resultados e histórico de análises. \n• Imagens: fotos dos olhos capturadas para análise. \n• Dados do dispositivo: modelo, sistema operacional, identificadores e rede.',
    priv_importante: 'Importante: Não coletamos dados sensíveis sem seu consentimento explícito. Suas informações são tratadas com confidencialidade e segurança.',
    priv_3_uso_titulo: '3. Uso das Informações',
    priv_3_uso_body: 'Utilizamos seus dados para: \n• Fornecer e aprimorar o serviço;\n• Processar imagens para triagem ocular;\n• Gerenciar seu perfil e histórico;\n• Enviar notificações importantes;\n• Cumprir obrigações legais.',
    priv_4_compartilhamento_titulo: '4. Compartilhamento',
    priv_4_compartilhamento_body: 'Suas informações podem ser compartilhadas com:\n• Profissionais de saúde (com consentimento);\n• Prestadores de serviço (armazenamento, processamento, etc.);\n• Pesquisadores (dados anonimizados);\n• Autoridades legais, se exigido.',
    priv_5_seguranca_titulo: '5. Segurança',
    priv_5_seguranca_body: 'Adotamos medidas técnicas e administrativas para proteger seus dados contra acessos não autorizados, alterações ou destruição.',
    priv_dica: 'Dica: Nunca compartilhe sua senha ou dados sensíveis com terceiros.',
    priv_6_direitos_titulo: '6. Seus Direitos',
    priv_6_direitos_body: 'Você pode acessar, corrigir ou excluir seus dados pessoais a qualquer momento. Para isso, envie um e-mail para: suporte@eyessistant.com',
    priv_7_retencao_titulo: '7. Retenção e Transferência',
    priv_7_retencao_body: 'Mantemos seus dados pelo tempo necessário para os fins desta Política, salvo obrigações legais. Dados podem ser processados em servidores fora do Brasil, sempre com proteção adequada.',
    priv_8_criancas_titulo: '8. Crianças',
    priv_8_criancas_body: 'O aplicativo não é destinado a menores de 18 anos. Não coletamos intencionalmente dados de crianças.',
    priv_9_alteracoes_titulo: '9. Alterações nesta Política',
    priv_9_alteracoes_body: 'Podemos atualizar esta Política periodicamente. Notificações serão feitas no app em caso de mudanças relevantes.',
    priv_10_contato_titulo: '10. Contato',
    priv_10_contato_body: 'Dúvidas? Fale conosco: suporte@eyessistant.com',
    priv_btn_entendi: 'Entendi e concordo',
    analise_titulo: 'Análise Ocular',
    analise_preparando: 'Preparando para Análise',
    analise_instrucoes: 'Posicione seu rosto na área indicada e mantenha os olhos abertos durante a análise.',
    analise_continuar: 'Continuar',
    analise_como_enviar: 'Como deseja enviar a imagem?',
    analise_tirar_foto: 'Tirar Foto',
    analise_galeria: 'Galeria',
    analise_escolher_galeria: 'Escolher da Galeria',
    analise_tirar_outra: 'Tirar outra foto',
    analise_confirmar: 'Confirmar',
    analise_escolher_outra: 'Escolher outra',
    analise_processando: 'Processando imagem na IA',
    analise_nenhum_sinal: 'Nenhum sinal detectado',
    analise_nenhum_sinal_desc: 'Não foram identificados sinais indicativos de catarata nesta análise.',
    analise_recomendacao_normal: 'Continue monitorando regularmente seus olhos com exames periódicos.',
    analise_recomendacao_urgente: 'Recomendamos que você consulte um oftalmologista para uma avaliação mais detalhada.',
    analise_recomendacao: 'Recomendação: Continue monitorando regularmente',
    analise_proximos_passos: 'Próximos Passos',
    analise_agendar_proxima: 'Agende sua próxima análise',
    analise_agendar_3_meses: 'Recomendamos a cada 3 meses',
    analise_detalhes: 'Detalhes da análise',
    analise_data: 'Data',
    analise_hora: 'Hora',
    analise_confianca: 'Nível de confiança',
    analise_olho_analisado: 'Olho analisado',
    analise_ambos: 'ambos',
    analise_salvar: 'salvar',
    analise_refazer: 'Refazer',
    analise_compartilhar: 'Compartilhar',
    analise_sinal_detectado: 'Possível sinal de catarata detectado',
    analise_confianca_label: 'Confiança',
    analise_agendar_oftalmologista: 'Consulte um oftalmologista urgentemente',
    analise_agendar_urgente: 'Procure um oftalmologista o quanto antes',
    analise_erro_titulo: 'Erro na análise',
    analise_erro_desc: 'Não foi possível processar a imagem',
    analise_tentar_novamente: 'Tentar novamente',
    analise_cancelar: 'Cancelar',
    analise_resultado: 'Resultado',
    analise_normal: 'Normal',
    analise_catarata: 'Catarata',
    analise_erro_desconhecido: 'Erro desconhecido',
    dados_titulo: 'Dashboard de Saúde Ocular',
    dados_total_analises: 'Total de Análises',
    dados_normais: 'Normais',
    dados_sinais_catarata: 'Sinais de catarata',
    dados_historico_completo: 'Ver histórico completo',
    dados_proporcao: 'Proporção de diagnósticos',
    acoes_rapidas: 'Ações rápidas',
    dados_dicas_prevencao: 'Dicas de prevenção',
    dados_consultar_especialista: 'Consultar especialista',
    perfil_ultima_consulta: 'Última Consulta Oftalmológica',
    perfil_data: 'Data',
    perfil_medico: 'Médico',
    perfil_meus_dados_visao: 'Meus Dados de Visão',
    perfil_versao: 'Versão',
    perfil_agendar_consulta: 'Agendar nova consulta',
    visao_nenhum_sinal: 'Nenhum sinal detectado',
    visao_continue_monitorando: 'continue monitorando regularmente',
    visao_possiveis_sinais: 'Possíveis sinais iniciais',
    visao_recomendamos_acompanhamento: 'recomendamos acompanhamento',
    visao_status_atual: 'Status atual da visão',
    visao_opacidade_inicial: 'Possível opacidade inicial',
    visao_ultima_atualizacao: 'Última atualização',
    visao_nenhum_problema: 'Nenhum problema detectado',
    visao_detalhes_diagnostico: 'Detalhes do Diagnóstico',
    visao_olho_esquerdo_opacidade: 'Olho Esquerdo: Possível opacidade inicial',
    visao_olho_direito_normal: 'Olho Direito: Nenhum problema detectado',
    visao_primeiro_sintoma: 'Primeiro sintoma detectado: 17/06/2025',
    visao_recomenda_oftalmologista: 'Recomendamos consultar um oftalmologista para uma avaliação mais detalhada.',
    visao_dica_pausas: 'Faça pausas regulares ao usar dispositivos eletrônicos',
    visao_boa_iluminacao: 'Mantenha uma boa iluminação ao ler ou trabalhar',
    visao_oculos_sol: 'Use óculos de sol em dias ensolarados para proteger seus olhos',
    visao_dieta_vitaminas: 'Mantenha uma dieta rica em vitaminas A, C e E',
    config_editar_perfil: 'Editar Perfil',
    config_altere_dados: 'Altere seus dados pessoais',
    config_tutorial: 'Tutorial',
    config_aprenda_usar: 'Aprenda a usar o aplicativo',
    config_analise_preferencias: 'Preferências de análise',
    config_receba_lembretes: 'Receba lembretes para realizar análises periódicas',
    config_preferencias_notificacoes: 'Preferências de Notificações',
    config_lembretes: 'Lembretes de análise',
    config_acompanhamento_medico: 'Acompanhamento médico',
    config_notificacoes_consultas: 'Notificações sobre consultas e acompanhamentos',
    config_acessibilidade: 'Acessibilidade',
    config_alto_contraste: 'Alto contraste',
    config_aumenta_contraste: 'Aumenta o contraste para melhor visualização',
    config_modo_daltonico: 'Modo daltônico',
    config_converte_cinza: 'Converte cores para escala de cinza',
    config_tema: 'Tema',
    config_alternar_claro_escuro: 'Alternar entre modo claro e escuro',
    config_privacidade_seguranca: 'Privacidade e Segurança',
    config_politica_privacidade: 'Política de Privacidade',
    config_ajuda_sobre: 'Ajuda / Sobre o App',
    config_sair_conta: 'Sair da Conta',
    config_sobre_eyessistant: 'Sobre o Eyessistant',
  },
  en: {
    
    voltar: 'Back',
    idioma: 'Language',
    portugues: 'Portuguese (Brazil)',
    english: 'English',
    spanish: 'Spanish',
    aplicacoes_idioma: 'Language settings will be applied immediately',
    configuracoes: 'Settings',
    editar_perfil: 'Edit Profile',
    alterar_dados: 'Change your personal information',
    cadastro_titulo: 'Sign Up',
    cadastro_passo1: 'Fill in your personal information',
    cadastro_passo2: 'Set your password and preferences',
    label_nome: 'Full name',
    label_email: 'Email',
    label_cpf: 'CPF',
    label_nascimento: 'Date of birth',
    label_telefone: 'Phone',
    label_senha: 'Password',
    label_confirmar_senha: 'Confirm password',
    cadastro_proxima_etapa: 'Next step',
    cadastro_cadastrar: 'Sign up',
    cadastro_voltar: 'Back',
    cadastro_erro_nome_curto: 'Name too short',
    placeholder_nome: 'Enter your full name',
    placeholder_email: 'Enter your email',
    placeholder_cpf: 'Enter your CPF',
    placeholder_nascimento: 'DD/MM/YYYY',
    placeholder_telefone: '(99) 99999-9999',
    placeholder_senha: 'Create a password',
    placeholder_confirmar_senha: 'Confirm your password',
    cadastro_li_concordo: 'I have read and agree to the',
    login_entrar: 'Log in',
    login_esqueci_senha: 'Forgot my password',
    login_nao_tem_conta: "Don't have an account?",
    ou_text: 'or',
    login_continuar_convidado: 'Continue as guest',
    cadastre_se: 'Sign up',
    nav_inicio: 'Home',
    nav_analise: 'Analysis',
    nav_dados: 'Data',
    nav_perfil: 'Profile',
    nav_config: 'Settings',
    inicio_ola_bemvindo: 'Hello, Welcome',
    inicio_subtitulo: 'Monitor the health of your eyes regularly',
    inicio_iniciar_analise: 'Start Analysis',
    inicio_analise_rapida: 'Quick analysis in less than 1 minute',
    tutorial_titulo: 'Tutorial',
    tutorial_desc: 'Learn how to use the app',
    tutorial_step1_title: 'Welcome to the Tutorial',
    tutorial_step1_desc: 'Let\'s learn how to perform an analysis using Eyessistant!\n\nThis tutorial shows step-by-step how to position the phone and take quality photos. If you are elderly or unfamiliar with smartphones, ask someone for help or follow each step carefully.',
    tutorial_step1_tip1: 'Choose a place with good diffuse lighting (do not point the face at direct light).',
    tutorial_step1_tip2: 'Sit in a comfortable chair with arm support.',
    tutorial_step1_tip3: 'Hold the phone securely or rest it on a stable surface (table, stand).',
    tutorial_step1_tip4: 'Take a deep breath and keep your gaze steady for a few seconds before capturing.',

    tutorial_step2_title: 'Ask for Help',
    tutorial_step2_desc: 'Having someone to help makes the process easier: the person can hold the phone, adjust the angle and ensure the eye is well framed. If you are alone, lean the phone against something stable.',
    tutorial_step2_tip1: 'Ask the helper to stand beside you and follow the app\'s guidance.',
    tutorial_step2_tip2: 'Explain that the eye should be centered in the frame and keep a distance of 10–15 cm.',
    tutorial_step2_tip3: 'Ask not to use flash directly on the eye (consistent lighting is better).',

    tutorial_step3_title: 'Position the Phone',
    tutorial_step3_desc: 'Sit comfortably and rest the phone on a stable surface to avoid shakes. Point the camera to the eye at a distance of 10–15 cm to ensure proper framing and focus. Keep the eye open, looking at the camera.',
    tutorial_step3_tip1: 'Remove glasses, contact lenses, hats or masks before capture.',
    tutorial_step3_tip2: 'Avoid very bright or very dark backgrounds behind the face (use a neutral wall when possible).',
    tutorial_step3_tip3: 'If focus is poor, move the phone slightly closer or farther until the image is sharp.',

    tutorial_step4_title: 'Upload and Analysis',
    tutorial_step4_desc: 'After capturing the image, it will be sent for analysis by our AI. Processing may take a few seconds to a few minutes depending on the connection. Meanwhile, do not close the app. When results appear, read carefully and follow recommendations.',
    tutorial_step4_tip1: 'Wait for the completion message before navigating to another screen.',
    tutorial_step4_tip2: 'Review the analysis details — if something seems wrong, retake the capture with better lighting.',
    tutorial_step4_tip3: 'If there is an indication of a problem, seek an ophthalmologist for an in-person evaluation.',

    dica_label: 'Tip:',
    sair: 'Exit',
    proximo: 'Next',
    finalizar: 'Finish',
    inicio_ultima_analise: 'Last Analysis',
    inicio_ver_todos: 'See all',
    historico_nenhum_sinal: 'No signs detected',
    historico_possiveis_sinais: 'Possible initial signs',
    dica_saude_titulo: 'Eye Health Tip',
    dica_saude_body: 'Taking regular breaks while using digital devices helps reduce eye strain.\nFollow the 20-20-20 rule: every 20 minutes, look at something 20 feet (6 meters) away for 20 seconds.',
    alert_preencha_campos: 'Please fill in all fields correctly.',
    alert_corrija_erros: 'Please fix the errors before continuing.',
    alert_preencha_aceite: 'Please fill in all fields and accept the terms.',
    email_invalido: 'Invalid email',
    cpf_invalido: 'Invalid CPF',
    data_invalida: 'Invalid date',
    telefone_invalido: 'Invalid phone number',
    senha_fraca: 'Weak password',
    senhas_nao_conferem: 'Passwords do not match',
    modal_cadastro_titulo: 'Sign up complete!',
    modal_cadastro_subtitulo: 'Your account was created successfully.',
    idioma_selecionado: 'English',
    meus_dados_visao: 'My Vision Data',
    visao_geral: 'Overview',
    historico: 'History',
    recomendacoes: 'Recommendations',
    status_atual: 'Current Vision Status',
    detalhes: 'Details',
    resumo_resultados: 'Results Summary',
    evolucao_resultados: 'Results Evolution',
    historico_completo: 'Full History',
    analises_por_mes: 'Analyses per Month',
    recomendacoes_personalizadas: 'Personalized Recommendations',
    consulta_recomendada: 'Recommended Ophthalmology Visit',
    proxima_triagem: 'Next Screening',
    ha_bitossaudaveis: 'Healthy Habits',
    saiba_mais: 'Learn More',
    o_que_e_catarata: 'What is cataract?',
    prevencao_catarata: 'Cataract prevention',
    tratamentos_disponiveis: 'Available treatments',
    normal: 'Normal',
    atencao: 'Attention',
    critico: 'Critical',
    jan: 'Jan',
    fev: 'Feb',
    mar: 'Mar',
    abr: 'Apr',
    mai: 'May',
    jun: 'Jun',
    encontrar_oftalmologistas_proximos: 'Find nearby ophthalmologists',
    analises_sem_sinais: '4 analyses without detected signs',
    analises_com_possiveis_sinais: '3 analyses with possible signs',
    catarata_body: 'Cataract is the clouding of the eye\'s natural lens (the crystalline lens) that reduces the amount of light reaching the retina. It can cause blurred vision, light sensitivity and difficulty seeing at night. It is common in older adults but can occur for other reasons.\n\nTypical signs and symptoms:\n• Blurred or hazy vision\n• Increased sensitivity to light\n• Difficulty seeing at night\n• Frequent changes in eyeglass prescription\n\nIf you notice these signs, seek an evaluation and guidance from an ophthalmologist.',
    prevencao_body: 'Measures that help reduce the risk or delay the progression of cataract:\n\n• UV protection: wear sunglasses with adequate UV protection whenever outdoors.\n• Avoid smoking: smoking increases the risk of developing various eye diseases.\n• Balanced diet: a diet rich in fruits and vegetables containing antioxidants (vitamins A, C, E) is beneficial.\n\n• Control chronic diseases: keep diabetes and blood pressure under control.\n• Regular exams: have regular ophthalmologic check-ups to detect changes early.\n\nThese measures do not guarantee absolute prevention but reduce known risk factors.',
    tratamentos_body: 'The definitive treatment for cataract is surgery, where the cloudy lens is removed and replaced with an intraocular lens (IOL).\n\nWhat to expect from surgery:\n• Procedure: usually performed with local anesthesia and quick recovery.\n• Risks and benefits: it is considered safe and effective, but discuss possible complications with the ophthalmologist.\n• Temporary alternatives: in early stages, changes in optical correction and improved lighting may temporarily improve vision.\n\nAfter surgery, it may take some time to adapt to the new lens; the ophthalmologist will guide about care and follow-up.'
    ,
    possivel_opacidade: 'Possible initial opacity',
    ultima_atualizacao: 'Last update',
    nenhum_problema: 'No problems detected',
    consulta_recomendacao_body: 'Based on your latest analyses, we recommend that you consult an ophthalmologist for a more detailed evaluation.',
    recomendamos_nova_triagem: 'We recommend scheduling a new screening in',
    agendar_lembrete: 'Schedule reminder',
    index_detecte_sinais: 'Detect cataract signs with AI assistance',
    index_subtitulo: 'A quick, accessible and intelligent exam, using only your phone camera.',
    index_analise_inteligente: 'Smart Analysis',
    index_tecnologia_ponta: 'Cutting-edge technology for early detection of cataract signs',
    index_monitoramento_continuo: 'Continuous Monitoring',
    index_acompanhe_saude: 'Monitor your eye health with periodic screenings',
    index_privacidade_garantida: 'Privacy Guaranteed',
    index_dados_protegidos: 'Your data is protected and we never share it without your permission',
    index_comecar_agora: 'Start Now',
    index_termos_politica: 'By continuing, you agree to our Terms of Use and Privacy Policy',
      index_termos_intro: 'By continuing, you agree to our',
      termos_uso: 'Terms of Use',
      e_text: 'and',
      politica_privacidade: 'Privacy Policy',
    sobre_app: 'About',
    sobre_o: 'About',
    sobre_o_eyessistant: 'About Eyessistant',
    sobre_o_que_e: 'What is it?',
    sobre_o_que_e_body: 'Eyessistant is an intelligent eye screening assistant that uses artificial intelligence to help detect early signs of cataract, using only your phone camera to analyze your eyes.',
    sobre_como_funciona: 'How it works?',
    sobre_analise_imagem: 'Image Analysis',
    sobre_analise_imagem_body: 'We use your phone camera to capture high-quality images of your eyes',
    sobre_inteligencia_artificial: 'Artificial Intelligence',
    sobre_inteligencia_body: 'Our AI analyzes patterns and identifies possible signs of cataract with high accuracy',
    sobre_privacidade: 'Privacy',
    sobre_privacidade_body: 'Your data is processed locally and protected with the highest security standards',
    sobre_por_que_usar: 'Why use Eyessistant?',
    sobre_por_que_usar_body: 'Cataract is one of the leading causes of treatable blindness worldwide. Early detection is crucial for effective treatment and to prevent vision loss. Eyessistant makes this process accessible to everyone, anytime.',
    sobre_disclaimer: 'Eyessistant does not replace a consultation with an eye care professional. Always consult a health professional for proper diagnosis and treatment.',
    editperfil_titulo: 'Edit Profile',
    editperfil_permissao_titulo: 'Permission required',
    editperfil_permissao_body: 'We need access to photos to change the profile picture.',
    editperfil_salvo_titulo: 'Saved',
    editperfil_salvo_body: 'Profile data updated.',
    editperfil_erro_titulo: 'Error',
    editperfil_erro_body: "Could not save the data.",
    alterar_foto: 'Change photo',
    placeholder_seu_nome: 'Your name',
    salvar: 'Save',
    perfil_nenhum_sinal: 'No signs detected',
    perfil_possiveis_sinais: 'Possible initial signs',
    perfil_continuar_monitorando: 'Continue monitoring regularly',
    perfil_ultima_consulta: 'Last Ophthalmology Visit',
    perfil_recomendamos_acompanhamento: 'We recommend follow-up',
    perfil_analises_recentes: 'Recent Analyses',
    perfil_editar: 'Edit',
    perfil_config: 'Settings',
    analise_titulo: 'Analysis',
    analise_tirar_foto: 'Take Photo',
    analise_galeria: 'Select from Gallery',
    analise_compartilhar: 'Share',
    analise_baixar: 'Download',
    analise_sinal_detectado: 'Possible sign of cataract detected',
    analise_confianca_label: 'Confidence',
    analise_agendar_oftalmologista: 'Consult an ophthalmologist urgently',
    analise_agendar_urgente: 'See an ophthalmologist as soon as possible',
    analise_erro_titulo: 'Analysis error',
    analise_erro_desc: 'Could not process the image',
    analise_tentar_novamente: 'Try again',
    analise_cancelar: 'Cancel',
    analise_resultado: 'Result',
    analise_normal: 'Normal',
    analise_catarata: 'Cataract',
    analise_erro_desconhecido: 'Unknown error',
    dados_info: 'Data',
    config_tema: 'Theme',
    config_claro: 'Light',
    config_escuro: 'Dark',
    config_contraste: 'Contrast Mode',
    config_daltonico: 'Colorblind Mode',
    config_tamanho_fonte: 'Font Size',
    termos_titulo: 'Terms of Use',
    termos_ultima_atualizacao: 'Last update: May 15, 2024',
    termos_1_aceitacao_titulo: '1. Acceptance of Terms',
    termos_1_aceitacao_body: 'By accessing and using the Eyessistant app, you agree to these Terms of Use. If you do not agree with any part of these terms, do not use the app.',
    termos_2_descricao_titulo: '2. Service Description',
    termos_2_descricao_body: 'Eyessistant is an eye screening app that uses artificial intelligence to identify possible signs of cataract. The app DOES NOT provide medical diagnoses and does not replace the advice of a qualified health professional.',
    termos_importante: 'Important: The results provided by the app are indicative only and should be clinically confirmed. Consult a health professional for evaluation and diagnosis.',
    termos_3_elegibilidade_titulo: '3. Eligibility and Registration',
    termos_3_elegibilidade_body: 'To use the app, you must:\n• Be at least 18 years old;\n• Provide accurate, current and complete information during registration;\n• Keep your registration information up to date;\n• Be responsible for the security of your account and password.',
    termos_4_uso_titulo: '4. Use of the App',
    termos_4_uso_body: 'By using the app you agree to:\n• Not use it for illegal or unauthorized purposes;\n• Not attempt to access restricted areas of the system;\n• Not interfere with or disrupt the operation of the app;\n• Not reproduce, copy, sell or exploit any part of the app;\n• Follow all instructions provided for proper use.',
    termos_5_limitacao_titulo: '5. Limitation of Liability',
    termos_5_limitacao_body: 'Eyessistant and its developers are not liable for any direct, indirect, incidental or consequential damages resulting from the use or inability to use the app. Use is at your own risk.',
    termos_6_propriedade_titulo: '6. Intellectual Property',
    termos_6_propriedade_body: 'All content, design, graphics, interfaces, code and software used in the app are the property of Eyessistant or its licensors. You are not permitted to copy, modify, distribute, sell or rent any part of the app.',
    termos_7_modificacoes_titulo: '7. Changes to the Terms',
    termos_7_modificacoes_body: 'We reserve the right to modify these Terms at any time. Changes take effect immediately after posting in the app or notifying users.',
    termos_8_lei_titulo: '8. Governing Law',
    termos_8_lei_body: 'These Terms are governed by and construed in accordance with the laws of Brazil. Any dispute will be subject to the exclusive jurisdiction of the courts of the city of São Paulo.',
    termos_9_contato_titulo: '9. Contact',
    termos_9_contato_body: 'Questions about these Terms? Contact us at: suporte@eyessistant.com',
    termos_entendi_concordo: 'I understand and agree',
    priv_politica_titulo: 'Privacy Policy',
    priv_ultima_atualizacao: 'Last update: September 13, 2025',
    priv_1_introducao_titulo: '1. Introduction',
    priv_1_introducao_body: 'Eyessistant is committed to protecting your privacy. This Policy describes how we collect, use, and protect your information when using the Eyessistant app.',
    priv_2_informacoes_titulo: '2. Information We Collect',
    priv_2_informacoes_body: '• Personal data: name, email, phone and CPF (when provided).\n• Health data: information about your vision, results and analysis history. \n• Images: photos of the eyes captured for analysis. \n• Device data: model, operating system, identifiers and network.',
    priv_importante: 'Important: We do not collect sensitive data without your explicit consent. Your information is treated with confidentiality and security.',
    priv_3_uso_titulo: '3. Use of Information',
    priv_3_uso_body: 'We use your data to:\n• Provide and improve the service;\n• Process images for eye screening;\n• Manage your profile and history;\n• Send important notifications;\n• Comply with legal obligations.',
    priv_4_compartilhamento_titulo: '4. Sharing',
    priv_4_compartilhamento_body: 'Your information may be shared with:\n• Healthcare professionals (with consent);\n• Service providers (storage, processing, etc.);\n• Researchers (anonymized data);\n• Legal authorities, if required.',
    priv_5_seguranca_titulo: '5. Security',
    priv_5_seguranca_body: 'We adopt technical and administrative measures to protect your data against unauthorized access, alteration or destruction.',
    priv_dica: 'Tip: Never share your password or sensitive data with third parties.',
    priv_6_direitos_titulo: '6. Your Rights',
    priv_6_direitos_body: 'You can access, correct or delete your personal data at any time. To do so, send an email to: suporte@eyessistant.com',
    priv_7_retencao_titulo: '7. Retention and Transfer',
    priv_7_retencao_body: 'We retain your data for as long as necessary for the purposes of this Policy, except as required by law. Data may be processed on servers outside Brazil, always with appropriate protections.',
    priv_8_criancas_titulo: '8. Children',
    priv_8_criancas_body: 'The app is not intended for persons under 18 years of age. We do not intentionally collect data from children.',
    priv_9_alteracoes_titulo: '9. Changes to this Policy',
    priv_9_alteracoes_body: 'We may update this Policy periodically. Notifications will be made in the app in case of relevant changes.',
    priv_10_contato_titulo: '10. Contact',
    priv_10_contato_body: 'Questions? Contact us: suporte@eyessistant.com',
    priv_btn_entendi: 'I understand and agree',
    analise_preparando: 'Preparing for Analysis',
    analise_instrucoes: 'Position your face in the indicated area and keep your eyes open during the analysis.',
    analise_continuar: 'Continue',
    analise_como_enviar: 'How would you like to send the image?',
    analise_escolher_galeria: 'Choose from Gallery',
    analise_tirar_outra: 'Take another photo',
    analise_confirmar: 'Confirm',
    analise_escolher_outra: 'Choose another',
    analise_processando: 'Processing image in AI',
    analise_nenhum_sinal_desc: 'No signs indicative of cataract were identified in this analysis.',
    analise_nenhum_sinal: 'No signs detected',
    analise_recomendacao_normal: 'Continue monitoring your eyes regularly with periodic screenings.',
    analise_recomendacao_urgente: 'We recommend that you consult an ophthalmologist for a more detailed evaluation.',
    analise_recomendacao: 'Recommendation: Continue monitoring regularly',
    analise_proximos_passos: 'Next Steps',
    analise_agendar_proxima: 'Schedule your next analysis',
    analise_agendar_3_meses: 'We recommend every 3 months',
    analise_detalhes: 'Analysis details',
    analise_data: 'Date',
    analise_hora: 'Time',
    analise_confianca: 'Confidence level',
    analise_olho_analisado: 'Eye analyzed',
    analise_ambos: 'both',
    analise_salvar: 'save',
    analise_refazer: 'Redo',
    dados_titulo: 'Eye Health Dashboard',
    dados_total_analises: 'Total Analyses',
    dados_normais: 'Normal',
    dados_sinais_catarata: 'Signs of cataract',
    dados_historico_completo: 'View full history',
    dados_proporcao: 'Proportion of diagnoses',
    acoes_rapidas: 'Quick Actions',
    dados_dicas_prevencao: 'Prevention tips',
    dados_consultar_especialista: 'Consult a specialist',
    perfil_data: 'Date',
    perfil_medico: 'Doctor',
    perfil_meus_dados_visao: 'My Vision Data',
    perfil_versao: 'Version',
    perfil_agendar_consulta: 'Schedule new consultation',
    visao_continue_monitorando: 'continue monitoring regularly',
    visao_recomendamos_acompanhamento: 'we recommend follow-up',
    visao_nenhum_sinal: 'No signs detected',
    visao_possiveis_sinais: 'Possible initial signs',
    visao_status_atual: 'Current vision status',
    visao_ultima_atualizacao: 'Last update',
    visao_nenhum_problema: 'No problems detected',
    visao_detalhes_diagnostico: 'Diagnostic Details',
    visao_olho_esquerdo_opacidade: 'Left Eye: Possible initial opacity',
    visao_olho_direito_normal: 'Right Eye: No problem detected',
    visao_primeiro_sintoma: 'First symptom detected: 17/06/2025',
    visao_recomenda_oftalmologista: 'We recommend consulting an ophthalmologist for a more detailed evaluation.',
    visao_dica_pausas: 'Take regular breaks when using electronic devices',
    visao_boa_iluminacao: 'Maintain good lighting when reading or working',
    visao_oculos_sol: 'Wear sunglasses on sunny days to protect your eyes',
    visao_dieta_vitaminas: 'Maintain a diet rich in vitamins A, C and E',
    config_altere_dados: 'Change your personal data',
    config_aprenda_usar: 'Learn how to use the app',
    config_analise_preferencias: 'Analysis preferences',
    config_receba_lembretes: 'Receive reminders to perform periodic analyses',
    config_preferencias_notificacoes: 'Notification Preferences',
    config_lembretes: 'Analysis reminders',
    config_acompanhamento_medico: 'Medical follow-up',
    config_notificacoes_consultas: 'Notifications about consultations and follow-ups',
    config_acessibilidade: 'Accessibility',
    config_alto_contraste: 'High contrast',
    config_aumenta_contraste: 'Increases contrast for better viewing',
    config_modo_daltonico: 'Colorblind mode',
    config_converte_cinza: 'Converts colors to grayscale',
    config_alternar_claro_escuro: 'Switch between light and dark mode',
    config_privacidade_seguranca: 'Privacy and Security',
    config_politica_privacidade: 'Privacy Policy',
    config_ajuda_sobre: 'Help / About the App',
    config_sair_conta: 'Sign Out',
    config_sobre_eyessistant: 'About Eyessistant',
  },
  es: {
    voltar: 'Volver',
    idioma: 'Idioma',
    portugues: 'Portugués (Brasil)',
    english: 'Inglés',
    spanish: 'Español',
    aplicacoes_idioma: 'La configuración de idioma se aplicará inmediatamente',
    configuracoes: 'Ajustes',
    editar_perfil: 'Editar Perfil',
    alterar_dados: 'Cambia tu información personal',
    cadastro_titulo: 'Registro',
    cadastro_passo1: 'Complete sus datos personales',
    cadastro_passo2: 'Configure su contraseña y preferencias',
    label_nome: 'Nombre completo',
    label_email: 'Correo electrónico',
    label_cpf: 'CPF',
    label_nascimento: 'Fecha de nacimiento',
    label_telefone: 'Teléfono',
    label_senha: 'Contraseña',
    label_confirmar_senha: 'Confirmar contraseña',
    cadastro_proxima_etapa: 'Siguiente paso',
    cadastro_cadastrar: 'Registrar',
    cadastro_voltar: 'Volver',
    cadastro_erro_nome_curto: 'Nombre demasiado corto',
    placeholder_nome: 'Complete sus datos personales',
    placeholder_email: 'Ingrese su correo electrónico',
    placeholder_cpf: 'Ingrese su CPF',
    placeholder_nascimento: 'DD/MM/AAAA',
    placeholder_telefone: '(99) 99999-9999',
    placeholder_senha: 'Cree una contraseña',
    placeholder_confirmar_senha: 'Confirme su contraseña',
    cadastro_li_concordo: 'He leído y acepto los',
    login_entrar: 'Iniciar sesión',
    login_esqueci_senha: 'Olvidé mi contraseña',
    login_nao_tem_conta: '¿No tienes una cuenta?',
    ou_text: 'o',
    login_continuar_convidado: 'Continuar como invitado',
    cadastre_se: 'Regístrate',
    nav_inicio: 'Inicio',
    nav_analise: 'Análisis',
    nav_dados: 'Datos',
    nav_perfil: 'Perfil',
    nav_config: 'Configuración',
    inicio_ola_bemvindo: 'Hola, Bienvenido(a)',
    inicio_subtitulo: 'Monitorea la salud de tus ojos regularmente',
    inicio_iniciar_analise: 'Iniciar Análisis',
    inicio_analise_rapida: 'Análisis rápido en menos de 1 minuto',
    tutorial_titulo: 'Tutorial',
    tutorial_desc: 'Aprende a usar la aplicación',
    tutorial_step1_title: 'Bienvenido al Tutorial',
    tutorial_step1_desc: 'Aprendamos a realizar un análisis usando Eyessistant!\n\nEste tutorial muestra paso a paso cómo posicionar el teléfono y tomar fotos de calidad. Si es mayor o tiene poca familiaridad con los smartphones, pida ayuda a alguien o siga cada paso con calma.',
    tutorial_step1_tip1: 'Elija un lugar con buena iluminación difusa (no apunte la cara hacia luz directa).',
    tutorial_step1_tip2: 'Siéntese en una silla cómoda con apoyo para los brazos.',
    tutorial_step1_tip3: 'Sostenga el teléfono con firmeza o apóyelo en una superficie estable (mesa, soporte).',
    tutorial_step1_tip4: 'Respire hondo y mantenga la mirada estable durante unos segundos antes de la captura.',

    tutorial_step2_title: 'Pida Ayuda',
    tutorial_step2_desc: 'Tener a alguien que ayude facilita el proceso: la persona puede sostener el teléfono, ajustar el ángulo y asegurar que el ojo esté bien enmarcado. Si está solo, apoye el teléfono contra algo estable.',
    tutorial_step2_tip1: 'Pida a la persona que se coloque a su lado y siga las indicaciones de la app.',
    tutorial_step2_tip2: 'Explique que se debe centrar el ojo en el cuadro y mantener una distancia de 10–15 cm.',
    tutorial_step2_tip3: 'Pida no usar flash directamente en el ojo (la iluminación constante es mejor).',

    tutorial_step3_title: 'Coloque el Teléfono',
    tutorial_step3_desc: 'Siéntese cómodamente y apoye el teléfono en una superficie estable para evitar movimientos. Apunte la cámara al ojo a una distancia de 10–15 cm para asegurar buen encuadre y enfoque. Mantenga el ojo abierto, mirando a la cámara.',
    tutorial_step3_tip1: 'Retire gafas, lentes de contacto, sombreros o mascarillas antes de la captura.',
    tutorial_step3_tip2: 'Evite fondos muy claros o muy oscuros detrás del rostro (use pared neutra cuando sea posible).',
    tutorial_step3_tip3: 'Si el enfoque está mal, mueva el teléfono un poco más cerca o más lejos hasta que la imagen esté nítida.',

    tutorial_step4_title: 'Envío y Análisis',
    tutorial_step4_desc: 'Después de capturar la imagen, se enviará para análisis por nuestra IA. El procesamiento puede tardar desde unos segundos hasta algunos minutos según la conexión. Mientras tanto, no cierre la app. Cuando aparezcan los resultados, léalos con atención y siga las recomendaciones.',
    tutorial_step4_tip1: 'Espere el mensaje de finalización antes de navegar a otra pantalla.',
    tutorial_step4_tip2: 'Revise los detalles del análisis — si algo parece incorrecto, repita la captura con mejor iluminación.',
    tutorial_step4_tip3: 'Si hay indicación de un problema, consulte a un oftalmólogo para una evaluación presencial.',

    dica_label: 'Consejo:',
    sair: 'Salir',
    proximo: 'Siguiente',
    finalizar: 'Finalizar',
    inicio_ultima_analise: 'Último Análisis',
    inicio_ver_todos: 'Ver todo',
    historico_nenhum_sinal: 'Ningún signo detectado',
    historico_possiveis_sinais: 'Posibles signos iniciales',
    dica_saude_titulo: 'Consejo de Salud Ocular',
    dica_saude_body: 'Hacer pausas regulares al usar dispositivos digitales ayuda a reducir la fatiga ocular.\nSigue la regla 20-20-20: cada 20 minutos, mira algo a 20 pies (6 metros) durante 20 segundos.',
    alert_preencha_campos: 'Por favor complete todos los campos correctamente.',
    alert_corrija_erros: 'Corrija los errores antes de continuar.',
    alert_preencha_aceite: 'Complete todos los campos y acepte los términos.',
    email_invalido: 'Correo inválido',
    cpf_invalido: 'CPF inválido',
    data_invalida: 'Fecha inválida',
    telefone_invalido: 'Teléfono inválido',
    senha_fraca: 'Contraseña débil',
    senhas_nao_conferem: 'Las contraseñas no coinciden',
    modal_cadastro_titulo: '¡Registro realizado!',
    modal_cadastro_subtitulo: 'Su cuenta fue creada con éxito.',
    idioma_selecionado: 'Español',
    meus_dados_visao: 'Mis Datos de Visión',
    visao_geral: 'Visión General',
    historico: 'Historial',
    recomendacoes: 'Recomendaciones',
    status_atual: 'Estado Actual de la Visión',
    detalhes: 'Detalles',
    resumo_resultados: 'Resumen de Resultados',
    evolucao_resultados: 'Evolución de Resultados',
    historico_completo: 'Historial Completo',
    dados_titulo: 'Panel de Salud Ocular',
    dados_proporcao: 'Proporción de diagnósticos',
    acoes_rapidas: 'Acciones rápidas',
    analises_por_mes: 'Análisis por Mes',
    recomendacoes_personalizadas: 'Recomendaciones Personalizadas',
    consulta_recomendada: 'Consulta Oftalmológica Recomendada',
    proxima_triagem: 'Próxima Revisión',
    ha_bitossaudaveis: 'Hábitos Saludables',
    saiba_mais: 'Aprende Más',
    o_que_e_catarata: '¿Qué es la catarata?',
    prevencao_catarata: 'Prevención de la catarata',
    tratamentos_disponiveis: 'Tratamientos disponibles',
    normal: 'Normal',
    atencao: 'Atención',
    critico: 'Crítico',
    jan: 'Ene',
    fev: 'Feb',
    mar: 'Mar',
    abr: 'Abr',
    mai: 'May',
    jun: 'Jun',
    encontrar_oftalmologistas_proximos: 'Encontrar oftalmólogos cercanos',
    analises_sem_sinais: '4 análisis sin signos detectados',
    analises_com_possiveis_sinais: '3 análisis con posibles signos',
    catarata_body: 'La catarata es la opacidad del cristalino (la lente natural del ojo) que reduce la cantidad de luz que llega a la retina. Puede causar visión borrosa, sensibilidad a la luz y dificultad para ver de noche. Es común en personas mayores, pero puede ocurrir por otras causas.\n\nSignos y síntomas típicos:\n• Visión borrosa o nublada\n• Aumento de la sensibilidad a la luz\n• Dificultad para ver de noche\n• Cambios frecuentes en la graduación de las gafas\n\nSi nota estos signos, consulte a un oftalmólogo para su evaluación y orientación.',
    prevencao_body: 'Medidas que ayudan a reducir el riesgo o retrasar la progresión de la catarata:\n\n• Protección UV: use gafas de sol con protección UV adecuada siempre que esté al aire libre.\n• Evitar el tabaco: fumar aumenta el riesgo de desarrollar diversas enfermedades oculares.\n• Alimentación equilibrada: una dieta rica en frutas y verduras que contengan antioxidantes (vitaminas A, C, E) es beneficiosa.\n\n• Control de enfermedades crónicas: mantenga la diabetes y la presión arterial bajo control.\n• Exámenes periódicos: realice evaluaciones oftalmológicas regulares para detectar alteraciones con antelación.\n\nEstas medidas no garantizan una prevención absoluta, pero reducen factores de riesgo conocidos.',
    tratamentos_body: 'El tratamiento definitivo para la catarata es la cirugía, donde se retira la lente opaca y se reemplaza por una lente intraocular (LIO).\n\nQué esperar de la cirugía:\n• Procedimiento: generalmente se realiza con anestesia local y recuperación rápida.\n• Riesgos y beneficios: se considera seguro y eficaz, pero discuta posibles complicaciones con el oftalmólogo.\n• Alternativas temporales: en fases iniciales, los cambios en la correcciones ópticas y una mejor iluminación pueden mejorar temporalmente la visión.\n\nDespués de la cirugía, puede ser necesario cierto tiempo para adaptarse a la nueva lente; el oftalmólogo orientará sobre cuidados y seguimiento.'
    ,
    possivel_opacidade: 'Opacidad inicial posible',
    ultima_atualizacao: 'Última actualización',
    nenhum_problema: 'Ningún problema detectado',
    consulta_recomendacao_body: 'Basado en sus últimos análisis, le recomendamos que consulte a un oftalmólogo para una evaluación más detallada.',
    recomendamos_nova_triagem: 'Recomendamos realizar una nueva revisión en',
    agendar_lembrete: 'Programar recordatorio',
    index_detecte_sinais: 'Detecte signos de catarata con la ayuda de la IA',
    index_subtitulo: 'Un examen rápido, accesible e inteligente, usando solo la cámara de su teléfono.',
    index_analise_inteligente: 'Análisis Inteligente',
    index_tecnologia_ponta: 'Tecnología de punta para la detección temprana de signos de catarata',
    index_monitoramento_continuo: 'Monitoreo Continuo',
    index_acompanhe_saude: 'Controle la salud de sus ojos con exámenes periódicos',
    index_privacidade_garantida: 'Privacidad Garantizada',
    index_dados_protegidos: 'Sus datos están protegidos y nunca los compartimos sin su permiso',
    index_comecar_agora: 'Comenzar Ahora',
    index_termos_politica: 'Al continuar, usted acepta nuestros Términos de Uso y Política de Privacidad',
      index_termos_intro: 'Al continuar, usted acepta nuestros',
      termos_uso: 'Términos de Uso',
      e_text: 'y',
      politica_privacidade: 'Política de Privacidad',
      analise_nenhum_sinal: 'Ningún signo detectado',
      analise_recomendacao_normal: 'Continúe monitoreando sus ojos regularmente con revisiones periódicas.',
      analise_recomendacao_urgente: 'Le recomendamos que consulte a un oftalmólogo para una evaluación más detallada.',
    analise_sinal_detectado: 'Posible signo de catarata detectado',
    analise_confianca_label: 'Confianza',
    analise_agendar_oftalmologista: 'Consulte a un oftalmólogo urgentemente',
    analise_agendar_urgente: 'Vea a un oftalmólogo lo antes posible',
    analise_error_titulo: 'Error en el análisis',
    analise_error_desc: 'No se pudo procesar la imagen',
    analise_tentar_novamente: 'Intentar de nuevo',
    analise_cancelar: 'Cancelar',
    analise_resultado: 'Resultado',
    analise_normal: 'Normal',
    analise_catarata: 'Catarata',
    analise_error_desconhecido: 'Error desconocido',
    sobre_app: 'Acerca de',
    priv_politica_titulo: 'Política de Privacidad',
    priv_ultima_atualizacao: 'Última actualización: 13 de septiembre de 2025',
    priv_1_introducao_titulo: '1. Introducción',
    priv_1_introducao_body: 'Eyessistant se compromete a proteger su privacidad. Esta Política describe cómo recopilamos, usamos y protegemos su información al utilizar la aplicación Eyessistant.',
    priv_2_informacoes_titulo: '2. Información que Recopilamos',
    priv_2_informacoes_body: '• Datos personales: nombre, correo electrónico, teléfono y CPF (cuando se proporcionen).\n• Datos de salud: información sobre su visión, resultados e historial de análisis. \n• Imágenes: fotos de los ojos capturadas para análisis. \n• Datos del dispositivo: modelo, sistema operativo, identificadores y red.',
    priv_importante: 'Importante: No recopilamos datos sensibles sin su consentimiento explícito. Su información se trata con confidencialidad y seguridad.',
    priv_3_uso_titulo: '3. Uso de la Información',
    priv_3_uso_body: 'Utilizamos sus datos para:\n• Proporcionar y mejorar el servicio;\n• Procesar imágenes para el cribado ocular;\n• Gestionar su perfil e historial;\n• Enviar notificaciones importantes;\n• Cumplir con obligaciones legales.',
    priv_4_compartilhamento_titulo: '4. Compartición',
    priv_4_compartilhamento_body: 'Su información puede ser compartida con:\n• Profesionales de la salud (con consentimiento);\n• Proveedores de servicios (almacenamiento, procesamiento, etc.);\n• Investigadores (datos anonimizados);\n• Autoridades legales, si es requerido.',
    priv_5_seguranca_titulo: '5. Seguridad',
    priv_5_seguranca_body: 'Adoptamos medidas técnicas y administrativas para proteger sus datos contra accesos no autorizados, alteraciones o destrucción.',
    priv_dica: 'Consejo: Nunca comparta su contraseña o datos sensibles con terceros.',
    priv_6_direitos_titulo: '6. Sus Derechos',
    priv_6_direitos_body: 'Puede acceder, corregir o eliminar sus datos personales en cualquier momento. Para ello, envíe un correo a: suporte@eyessistant.com',
    priv_7_retencao_titulo: '7. Retención y Transferencia',
    priv_7_retencao_body: 'Mantenemos sus datos durante el tiempo necesario para los fines de esta Política, salvo obligaciones legales. Los datos pueden procesarse en servidores fuera de Brasil, siempre con protección adecuada.',
    priv_8_criancas_titulo: '8. Niños',
    priv_8_criancas_body: 'La aplicación no está destinada a menores de 18 años. No recopilamos intencionalmente datos de niños.',
    priv_9_alteracoes_titulo: '9. Cambios en esta Política',
    priv_9_alteracoes_body: 'Podemos actualizar esta Política periódicamente. Se realizarán notificaciones en la aplicación en caso de cambios relevantes.',
    priv_10_contato_titulo: '10. Contacto',
    priv_10_contato_body: '¿Dudas? Contáctenos: suporte@eyessistant.com',
    priv_btn_entendi: 'Entiendo y acepto',
    sobre_o: 'Acerca de',
    sobre_o_eyessistant: 'Acerca de Eyessistant',
    sobre_o_que_e: '¿Qué es?',
    sobre_o_que_e_body: 'Eyessistant es un asistente inteligente de cribado ocular que utiliza inteligencia artificial para ayudar a detectar signos tempranos de catarata, utilizando solo la cámara de su teléfono para analizar sus ojos.',
    sobre_como_funciona: '¿Cómo funciona?',
    sobre_analise_imagem: 'Análisis de Imagen',
    sobre_analise_imagem_body: 'Utilizamos la cámara de su teléfono para capturar imágenes de alta calidad de sus ojos',
    sobre_inteligencia_artificial: 'Inteligencia Artificial',
    sobre_inteligencia_body: 'Nuestra IA analiza patrones e identifica posibles signos de catarata con alta precisión',
    sobre_privacidade: 'Privacidad',
    sobre_privacidade_body: 'Sus datos se procesan localmente y están protegidos con los más altos estándares de seguridad',
    sobre_por_que_usar: '¿Por qué usar Eyessistant?',
    sobre_por_que_usar_body: 'La catarata es una de las principales causas de ceguera tratable en el mundo. La detección temprana es fundamental para un tratamiento eficaz y para prevenir la pérdida de visión. Eyessistant hace que este proceso sea accesible para todos, en cualquier momento.',
    sobre_disclaimer: 'Eyessistant no sustituye una consulta con un oftalmólogo. Siempre consulte a un profesional de la salud para un diagnóstico y tratamiento adecuados.',
    editperfil_titulo: 'Editar Perfil',
    editperfil_permissao_titulo: 'Permiso necesario',
    editperfil_permissao_body: 'Necesitamos acceso a las fotos para cambiar la foto de perfil.',
    editperfil_salvo_titulo: 'Guardado',
    editperfil_salvo_body: 'Datos del perfil actualizados.',
    editperfil_erro_titulo: 'Error',
    editperfil_erro_body: 'No se pudieron guardar los datos.',
    alterar_foto: 'Cambiar foto',
    placeholder_seu_nome: 'Tu nombre',
    salvar: 'Guardar',
    perfil_nenhum_sinal: 'Ningún signo detectado',
    perfil_possiveis_sinais: 'Posibles signos iniciales',
    perfil_continuar_monitorando: 'Continúe monitoreando regularmente',
    perfil_ultima_consulta: 'Última consulta oftalmológica',
    perfil_recomendamos_acompanhamento: 'Recomendamos seguimiento',
    perfil_analises_recentes: 'Análisis Recientes',
    perfil_editar: 'Editar',
    perfil_config: 'Configuración',
    termos_titulo: 'Términos de Uso',
    termos_ultima_atualizacao: 'Última actualización: 15 de mayo de 2024',
    termos_1_aceitacao_titulo: '1. Aceptación de los Términos',
    termos_1_aceitacao_body: 'Al acceder y utilizar la aplicación Eyessistant, usted acepta estos Términos de Uso. Si no está de acuerdo con alguna parte de estos términos, no utilice la aplicación.',
    termos_2_descripcion_titulo: '2. Descripción del Servicio',
    termos_2_descricao_body: 'Eyessistant es una aplicación de cribado ocular que utiliza inteligencia artificial para identificar posibles signos de catarata. La aplicación NO proporciona diagnósticos médicos y no sustituye el consejo de un profesional de la salud calificado.',
    termos_importante: 'Importante: Los resultados proporcionados por la aplicación son solo indicativos y deben confirmarse clínicamente. Consulte a un profesional de la salud para evaluación y diagnóstico.',
    termos_3_elegibilidade_titulo: '3. Elegibilidad y Registro',
    termos_3_elegibilidade_body: 'Para utilizar la aplicación, debe:\n• Tener al menos 18 años de edad;\n• Proporcionar información precisa, actual y completa durante el registro;\n• Mantener su información de registro actualizada;\n• Ser responsable de la seguridad de su cuenta y contraseña.',
    termos_4_uso_titulo: '4. Uso de la Aplicación',
    termos_4_uso_body: 'Al utilizar la aplicación, usted acepta: \n• No usarla para fines ilegales o no autorizados;\n• No intentar acceder a áreas restringidas del sistema;\n• No interferir o interrumpir el funcionamiento de la aplicación;\n• No reproducir, copiar, vender o explotar ninguna parte de la aplicación;\n• Seguir todas las instrucciones proporcionadas para el uso adecuado.',
    termos_5_limitacao_titulo: '5. Limitación de Responsabilidad',
    termos_5_limitacao_body: 'Eyessistant y sus desarrolladores no son responsables de ningún daño directo, indirecto, incidental o consecuente derivado del uso o la incapacidad de usar la aplicación. El uso es bajo su propio riesgo.',
    termos_6_propriedade_titulo: '6. Propiedad Intelectual',
    termos_6_propriedade_body: 'Todo el contenido, diseño, gráficos, interfaces, código y software utilizados en la aplicación son propiedad de Eyessistant o de sus licenciantes. No tiene permiso para copiar, modificar, distribuir, vender o alquilar ninguna parte de la aplicación.',
    termos_7_modificacoes_titulo: '7. Modificaciones de los Términos',
    termos_7_modificacoes_body: 'Nos reservamos el derecho de modificar estos Términos en cualquier momento. Los cambios entran en vigor inmediatamente después de su publicación en la aplicación o notificación a los usuarios.',
    termos_8_lei_titulo: '8. Ley Aplicable',
    termos_8_lei_body: 'Estos Términos se rigen e interpretan de acuerdo con las leyes de Brasil. Cualquier disputa se someterá a la jurisdicción exclusiva de los tribunales de la ciudad de São Paulo.',
    termos_9_contato_titulo: '9. Contacto',
    termos_9_contato_body: '¿Dudas sobre estos Términos? Póngase en contacto por correo electrónico: suporte@eyessistant.com',
    termos_entendi_concordo: 'Entendi e concordo',
  },
};

const IdiomaContext = createContext<IdiomaContextType>({
  idioma: 'pt',
  setIdioma: () => {},
  t: (k) => k,
});

export const IdiomaProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [idioma, setIdiomaState] = useState<Lang>('pt');

  useEffect(() => {
    (async () => {
      try {
        const stored = await AsyncStorage.getItem('@eyessistant_idioma');
        if (stored === 'pt' || stored === 'en' || stored === 'es') setIdiomaState(stored as Lang);
      } catch (e) {
        // ignore
      }
    })();
  }, []);

  const setIdioma = (l: Lang) => {
    setIdiomaState(l);
    AsyncStorage.setItem('@eyessistant_idioma', l).catch(() => {});
  };

  const t = (key: string) => {
    return translations[idioma][key] ?? translations['pt'][key] ?? key;
  };

  return <IdiomaContext.Provider value={{ idioma, setIdioma, t }}>{children}</IdiomaContext.Provider>;
};

export const useIdioma = () => useContext(IdiomaContext);

export default IdiomaContext;
